spring:
# 服务名称
  application:
    name: repo

  profiles:
    active: dev
  freemarker:
      cache: false
      charset: UTF-8
      template-loader-path: classpath:/templates/
      suffix: .html
      expose-request-attributes: true
      request-context-attribute: request
      settings:
        number_format: "#"
  messages:
    basename: i18n/messages
  servlet:
    multipart:
      max-file-size: -1
logging:
  path: /var/log/wx
  level:
    com.example.miaosha_idea: TRACE
    org.springframework: WARN
server:
  port: 8080
  servlet:
    context-path: /repo

excel:
  filePath: dataMap.json