spring:
# 服务名称
  application:
    name: repo

  profiles:
    active: dev
  freemarker:
      cache: false
      charset: UTF-8
      template-loader-path: classpath:/templates/
      suffix: .html
      expose-request-attributes: true
      request-context-attribute: request
      settings:
        number_format: "#"
  messages:
    basename: i18n/messages
  servlet:
    multipart:
      max-file-size: -1
logging:
  file: log/repo.log
  level:
    cn.demo.repo: TRACE
    org.springframework: WARN

server:
  port: 8080
  servlet:
    context-path: /repo

excel:
  filePath: dataMap.json
  fileName: 易耗品管理
  fileParam: 服务用具,0,7/礼品包装8,10/陈列部-货架顶端灯片,11,12/其他,13,16